version: '3.4'
services:
  mysql:
    image: mysql/mysql-server:5.7
    container_name: wallet_mysql
    networks:
      default:
        ipv4_address: 192.168.2.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: wallet
      MYSQL_USER: wallet
      MYSQL_PASSWORD: wallet
    ports:
      - '9906:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wallet_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    networks:
      default:
        ipv4_address: 192.168.2.4
    ports:
      - "81:80"

  web:
    build: ./.docker
    container_name: wallet_web
    networks:
      default:
        ipv4_address: 192.168.2.2
    volumes:
      - ./:/var/www/html/
      - ./.docker/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - '80:80'
    depends_on:
      - 'mysql'

  mailhog:
    image: mailhog/mailhog
    container_name: wallet_mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      default:
        ipv4_address: 192.168.2.5

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24
